### ISSUE TITLE
Cannot start "rake" on OSX 10.11.2

### ISSUE THREAD

**Issue by pcace** [bassnode/Echotunes#1]
Hi, 

i am trying to get "Echotunes" to run on my MacPro running 10.11.2. I am getting this error message: 

```
rake
ruby app.rb
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mr_eko'. (Bundler::GemRequireError)
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
    from app.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby app.rb...]
/Users/hannes/Desktop/Echotunes/Rakefile:6:in `block in <top (required)>'
Tasks: TOP => default => start
(See full trace by running task with --trace)
```

Any Idea what the Problem could be? 

Thanks a lot,

Pcace

**Comment by bassnode** [comment]
Looks like it's having problems loading a dependency.  Have you run `bundle install` recently?

Can you run this command successfully?

``` bash
gem install mr_eko
```

**Comment by pcace** [comment]
Hey, after i changed " json (1.8.1)" in the Gemfile.lock to "json (1.8.3)" i got a littlebit further:

```
bundle install
Using hashie 3.3.1
Using httpclient 2.4.0
Using libxml-ruby 2.7.0
Using coderay 1.0.5
Using plist 3.1.0
Using json 1.8.3
Using method_source 0.7.0
Using ruby-mp3info 0.8.5
Using sequel 3.15.0
Using sqlite3 1.3.9
Using slop 2.4.4
Using rack 1.4.1
Using redis 2.2.2
Using tilt 1.3.3
Using bundler 1.11.2
Using bassnode-ruby-echonest 0.1.3
Using itunes-library 0.1.0 from https://github.com/kylewelsby/itunes-library.git (at master@e4a85d7)
Using sqlite3-ruby 1.3.3
Using pry 0.9.8.2
Using rack-protection 1.2.0
Using shotgun 0.9
Using mr_eko 0.7.3
Using sinatra 1.3.2
Using sinatra-outputbuffer 0.1.0
Bundle complete! 8 Gemfile dependencies, 24 gems now installed.
Use bundle show [gemname] to see where a bundled gem is installed.
```

and then when starting rake:

```
rake
ruby app.rb
Caching library
/Users/hannes/Desktop/Echotunes/lib/setup.rb:11:in `cache!': uninitialized constant ITunes (NameError)
    from /Users/hannes/Desktop/Echotunes/lib/setup.rb:28:in `<top (required)>'
    from app.rb:6:in `require_relative'
    from app.rb:6:in `<main>'
rake aborted!
Command failed with status (1): [ruby app.rb...]
/Users/hannes/Desktop/Echotunes/Rakefile:6:in `block in <top (required)>'
Tasks: TOP => default => start
(See full trace by running task with --trace)
```

Since i have my iTunes Lib on an other place, i have changed the following lines in setup.rb to:

```
if ENV['FORCE'] || !already_cached?
  cache! 'Volumes/Media/iTunes/iTunes\ Library.xml'
else
```

Is the Problem the change of the path? ( i also tried this without any luck:)

```
Volumes/Media/iTunes/iTunes Library.xml
```

Thanks a lot for your help,

Pcace

**Comment by bassnode** [comment]
try this:

`File.expand_path("/Volumes/Media/iTunes/iTunes Library.xml")`

**Comment by pcace** [comment]
Still getting the same Error :(

```
 rake
ruby app.rb
Caching library
/Users/hannes/Desktop/Echotunes_1/lib/setup.rb:11:in `cache!': uninitialized constant ITunes (NameError)
    from /Users/hannes/Desktop/Echotunes_1/lib/setup.rb:28:in `<top (required)>'
    from app.rb:6:in `require_relative'
    from app.rb:6:in `<main>'
rake aborted!
Command failed with status (1): [ruby app.rb...]
/Users/hannes/Desktop/Echotunes_1/Rakefile:6:in `block in <top (required)>'
Tasks: TOP => default => start
(See full trace by running task with --trace)
```

By the Way, do you know any other Software (preferably Opensource) wich uses Echonest to generate playlists?

**Comment by pcace** [comment]
Hey, first of all, thank you for your help!
I think its either a bug in mr_eko or in my ruby install. Whenever i do a "gem install mr_eko" i do get a successfull installation, but when reading the log it sais at one point: 

```
unknown encoding name ":UTF_8" for lib/mr_eko.rb, skipping
```

which for me looks like it sais it installed mr_eko, but it really doesnt...

Pcace

**Comment by bassnode** [comment]
Can you tell me your platform information?  OS, ruby interpreter and version?

As for EN playlists - I don't know of any OSS that generates playlists.  The EN API itself can generate playlists with a seed catalog or artist. http://developer.echonest.com/docs/v4/playlisting.html

Paul Lamere from Echonest (and now, Spotify) blogs about a lot of his music applications: http://musicmachinery.com
Many of them are used in creating playlists, although I haven't seen one like Echotunes (i.e., creates playlists from _your_ music only).

**Comment by pcace** [comment]
Hi, after quiet some time, i tried to get this to run again... with the same results :/
Maybe you hve the time to help a little?  this is the output when doing rake --trace. Any Idea?

rake --trace
*\* Invoke default (first_time)
*\* Invoke start (first_time)
*\* Execute start
ruby app.rb
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mr_eko'. (Bundler::GemRequireError)
    from /Users/user/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
    from /Users/user/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
    from /Users/user/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in`block in require'
    from /Users/hannes/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
    from /Users/user/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`require'
    from /Users/user/.rvm/gems/ruby-1.9.3-p448/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
    from app.rb:4:in`<main>'
rake aborted!
Command failed with status (1): [ruby app.rb...]
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/file_utils.rb:54:in `block in create_shell_runner'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/file_utils.rb:45:in`sh'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/user/Desktop/Echotunes-master/Rakefile:6:in`block in <top (required)>'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:235:in`each'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:199:in`each'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:178:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:150:in`invoke_task'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:106:in`each'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:115:in`run_with_threads'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:78:in`block in run'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/lib/rake/application.rb:75:in`run'
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in`load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => default => start

**Comment by bassnode** [comment]
Can you tell me your platform information? OS, ruby interpreter and version?

**Comment by pcace** [comment]
Hey,

i hope this is the information you  are looking for:

`Klapperkiste-3:~ user$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.3
BuildVersion:   15D21
Klapperkiste-3:~ user$ rails -v
Rails 3.2.19
Klapperkiste-3:~ user$ rvm -v
rvm 1.25.32 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Klapperkiste-3:~ user$`

**Comment by bassnode** [comment]
Don't see a ruby version there.  Try this in the mreko directory:
`ruby -v`

**Comment by pcace** [comment]
Ok sorry, here it is:
`pwd
/Users/user/.rvm/gems/ruby-1.9.3-p448/gems/mr_eko-0.7.3/lib/mr_eko
Klapperkiste-3:mr_eko user$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
Klapperkiste-3:mr_eko user$ 
`

**Comment by bassnode** [comment]
I'm able to start the app w/ your same ruby version.
That said, after Echotunes boots and tries to create a playlist on Echonest, I get an API error.  Their catalog API seems to have changed.  I'll make this a bug and try to find time to look into it.
